on: [push]

jobs:
  scan-graphql:
    runs-on: ubuntu-latest
    name: Scan graphql endpoint
    steps:
      - uses: actions/checkout@v4
      - id: graphql
        name: Run graphql-cop 
        uses: vechain/graphql-cop-gitaction@main
        with:
          graphql-app: 'https://api.dev.marketplace.vechain.org/graphql'
      
